spring:
  application:
    name: cloud-storage
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false
  session:
    store-type: redis
    timeout: 24h
    redis:
      namespace: spring:session
      flush-mode: on-save
springdoc:
  swagger-ui:
    persist-authorization: true
    with-credentials: true
server:
  servlet:
    session:
      cookie:
        name: SESSION
        http-only: true
        same-site: lax
        secure: false